<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-25T19:11:05 GMT-05:00" name="citi Session Test suite" finished-at="2021-01-25T19:11:57 GMT-05:00" duration-ms="52226">
    <groups>
    </groups>
    <test started-at="2021-01-25T19:11:05 GMT-05:00" name="citi Testcases" finished-at="2021-01-25T19:11:57 GMT-05:00" duration-ms="52226">
      <class name="com.citi.testcases.HomePageTestCase">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.citi.testcases.HomePageTestCase@61386958]" started-at="2021-01-25T19:11:05 GMT-05:00" name="setUp" finished-at="2021-01-25T19:11:26 GMT-05:00" duration-ms="21393" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="mydemotest2()[pri:0, instance:com.citi.testcases.HomePageTestCase@61386958]" started-at="2021-01-25T19:11:26 GMT-05:00" name="mydemotest2" finished-at="2021-01-25T19:11:26 GMT-05:00" duration-ms="19" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mydemotest2 -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.citi.testcases.HomePageTestCase@61386958]" started-at="2021-01-25T19:11:26 GMT-05:00" name="setUp" finished-at="2021-01-25T19:11:57 GMT-05:00" duration-ms="30707" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyTitle()[pri:0, instance:com.citi.testcases.HomePageTestCase@61386958]" started-at="2021-01-25T19:11:57 GMT-05:00" name="verifyTitle" finished-at="2021-01-25T19:11:57 GMT-05:00" duration-ms="49" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [cc] but found [Property for Sale in London - Buy Properties in London - Zoopla]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [cc] but found [Property for Sale in London - Buy Properties in London - Zoopla]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.citi.testcases.HomePageTestCase.verifyTitle(HomePageTestCase.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
      </class> <!-- com.citi.testcases.HomePageTestCase -->
    </test> <!-- citi Testcases -->
  </suite> <!-- citi Session Test suite -->
</testng-results>
